### ISSUE TITLE
This module incorrectly reports `false` if the Server service has not been started

### ISSUE THREAD

**Issue by jviotti** [sindresorhus/is-admin#3]
Running `net.exe session` results in the following error message:

```sh
C:\Users\jviotti\Projects\is-admin>net.exe session
The Server service is not started.

More help is available by typing NET HELPMSG 2114.

C:\Users\jviotti\Projects\is-admin>echo %ERRORLEVEL%
2
```

The exit code is 2, so I think this module could either ensure that a non successful exit code results in a promise rejection rather than simply returning `false`, or we should add a fallback in case the user has this service disabled.

What do you think?

**Comment by jviotti** [comment]
Oh, this particular issue was discussed in the SO question you're linking to in the source code: http://stackoverflow.com/a/21295806. In summary, we can run:

```sh
fsutil dirty query %systemdrive% >nul
```

And check the exit code. I confirm that works for me ^.

I guess we can either use that command instead of the current `net.exe` approach, or use it as a fallback. Have you read that answer before? Do you know of any case where `fsutil` will not work?

**Comment by jviotti** [comment]
Hm, the `net.exe` command returns an exit code 2 when the user has no privileges, but also when the server service is disabled, which means there is no clear way to distinguish between those two scenarios without inspecting the command output, which doesn't sound very nice.

If you're happy with the `fsutil` approach, this works beautifully for me:

```diff
diff --git a/index.js b/index.js
index 3166213..92aa6e9 100644
--- a/index.js
+++ b/index.js
@@ -7,5 +7,5 @@ module.exports = () => {
        }

        // http://stackoverflow.com/a/11995662/64949
-       return execa('net.exe', ['session']).then(() => true).catch(() => false);
+       return execa('fsutil', ['dirty', 'query', '%systemdrive%']).then(() => true).catch(() => false);
 };
```

**Comment by sindresorhus** [comment]
Good research :) How about `fsutil` first, then `net` as a fallback if it doesn't work? Wanna do a pull request?

**Comment by jviotti** [comment]
How would we determine whether we should run the fallback or not? The `fsutil` command returns an exit code 1 if the user is not an admin, and 0 otherwise. 

If we run `net.exe` when `fsutil` returns 1, then we would be ignoring the result of `fsutil` altogether (and eventually getting the server service error anyway).

**Comment by lurch** [comment]
By 'fallback' perhaps @sindresorhus meant if the `fsutil` command isn't available? The SO answer you linked to says "Windows 2000 and Windows PE (Preinstalled Environment) don't come with fsutil.exe, so we have to resort to something else.". But even then it recommends using `sfc` instead of `net`, so perhaps the `net` code should be removed entirely?

**Comment by sindresorhus** [comment]
No I mean if `fsutil` does not exists, unless we can be sure it's always included?

**Comment by jviotti** [comment]
Oh, I see. Sounds good, I'll prepare a PR later today.

**Comment by jviotti** [comment]
I've submitted a PR: https://github.com/sindresorhus/is-admin/pull/4. Happy to address any code-styling preferences!

**Comment by Daniel15** [comment]
It feels pretty fragile to execute a command just to tell if the process is elevated... Is there no Win32 API call for this that we could call using node-ffi?

**Comment by sindresorhus** [comment]
@Daniel15 There might be API calls, but node-ffi is a native module and requires compiling, which is especially problematic on Windows as you need to install Visual Studio, Python, and more. Not very nice for a reusable module. That's why I have a personal policy never to use dependencies with native addons in reusable modules. They just create an awful experience for users. Node.js team has indicated they're planning native FFI support at some point, and then this will be more feasible. Until then, this works fine.

**Comment by Daniel15** [comment]
Thanks for the reply, @sindresorhus!

>  Node.js team has indicated they're planning native FFI support at some point

This would be really nice. It's one of the main pain points with Node.js at the moment - Using native code is pretty difficult, significantly more difficult than in other languages. `node-gyp` is not very friendly at all.

**Comment by sindresorhus** [comment]
@Daniel15 I've been begging for FFI for years. I have so many modules where I need to spawn binaries because of lack of it. Interacting with the OS is just so much easier in for example Python.

See https://twitter.com/sindresorhus/status/841348582011621376 and https://twitter.com/bmeurer/status/839212482405281795
